on:
  push:
    paths:
      - conf.d/keyboard/**
      - .github/workflows/keyboard.yaml

name: Build Keyboard Firmware

defaults:
  run:
    working-directory: ./conf.d

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l keyboard

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Corne Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/conf.d/keyboard"

      - name: Corne DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp

      - name: Corne Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_left_nice_nano_v2.uf2

      - name: Archive (Corne Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: conf.d/corne_left_nice_nano_v2.uf2

      - name: West Build (Corne Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/conf.d/keyboard"

      - name: Corne Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corne_right_nice_nano_v2.uf2

      - name: Archive (Corne Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: conf.d/corne_right_nice_nano_v2.uf2
